export const SUPPORTED_FONT_WEIGHTS = [100, 200, 300, 400, 500, 600, 700, 800, 900] as const;

export const SUPPORTED_FONT_FAMILIES = [
  "Arial",
  "Arial Black",
  "Big Shoulders Inline Display Variable",
  "Caveat Variable",
  "Comfortaa Variable",
  "Comic Sans MS",
  "Courier New",
  "Dancing Script Variable",
  "Darker Grotesque Variable",
  "Edu NSW ACT Foundation Variable",
  "Figtree Variable",
  "Fraunces Variable",
  "Georgia",
  "Impact",
  "Inter Variable",
  "Jost Variable",
  "Manrope Variable",
  "Merienda Variable",
  "Montserrat Variable",
  "Newsreader Variable",
  "Open Sans Variable",
  "Outfit Variable",
  "Red Hat Display Variable",
  "Roboto Mono Variable",
  "Sora Variable",
  "Space Grotesk Variable",
  "Syne Variable",
  "Times New Roman",
  "Trebuchet MS",
  "Urbanist Variable",
  "Verdana",
] as const;