#version 300 es
precision highp float;
// Adapted from web-fsr; see LICENSE.web-fsr. RGBA, bounded denominators and full ring/center limiter.
/*
  Original:https://www.shadertoy.com/view/stXSWB
  by goingdigital
*/

uniform vec2 iResolution;
uniform float sharpness;
uniform sampler2D iChannel0;
// uniform sampler2D iChannel1;
out vec4 fragColor;

/*
* FidelityFX Super Resolution scales up a low resolution
* image, while adding fine detail.
*
* MIT Open License
*
* https://gpuopen.com/fsr
*
* Left: FSR processed
* Right: Original texture, bilinear interpolation
*
* Mouse at top: Sharpness 0 stops (maximum)
* Mouse at bottom: Sharpness 2 stops (minimum)
*
* It works in two passes-
*   EASU upsamples the image with a clamped Lanczos kernel.
*   RCAS sharpens the image at the target resolution.
*
* I needed to make a few changes to improve readability and
* WebGL compatibility in an algorithm I don't fully understand.
* Expect bugs.
*
* Shader not currently running for WebGL1 targets (eg. mobile Safari)
*
* There is kind of no point to using FSR in Shadertoy, as it renders buffers
* at full target resolution. But this might be useful for WebGL based demos
* running smaller-than-target render buffers.
*
* For sharpening with a full resolution render buffer,
* FidelityFX CAS is a better option.
* https://www.shadertoy.com/view/ftsXzM
*
* For readability and compatibility, these optimisations have been removed:
*   * Fast approximate inverse and inversesqrt
*   * textureGather fetches (not WebGL compatible)
*   * Multiplying by reciprocal instead of division
*
* Apologies to AMD for the numerous slowdowns and errors I have introduced.
*
*/

/***** RCAS *****/
#define FSR_RCAS_LIMIT (0.25-(1.0/16.0))
//#define FSR_RCAS_DENOISE

// Input callback prototypes that need to be implemented by calling shader
vec4 FsrRcasLoadF(vec2 p);
//------------------------------------------------------------------------------------------------------------------------------
void FsrRcasCon(
    out float con,
    // The scale is {0.0 := maximum, to N>0, where N is the number of stops (halving) of the reduction of sharpness}.
    float sharpness
){
    // Transform from stops to linear value.
    con = exp2(-sharpness);
}

vec4 FsrRcasF(
    vec2 ip, // Integer pixel position in output.
    float con
)
{
    // Constant generated by RcasSetup().
    // Algorithm uses minimal 3x3 pixel neighborhood.
    //    b
    //  d e f
    //    h
    vec2 sp = vec2(ip);
    vec4 b = FsrRcasLoadF(sp + vec2( 0,-1));
    vec4 d = FsrRcasLoadF(sp + vec2(-1, 0));
    vec4 e = FsrRcasLoadF(sp);
    vec4 f = FsrRcasLoadF(sp+vec2( 1, 0));
    vec4 h = FsrRcasLoadF(sp+vec2( 0, 1));
    // Luma times 2.
    float bL = b.g + .5 * (b.b + b.r);
    float dL = d.g + .5 * (d.b + d.r);
    float eL = e.g + .5 * (e.b + e.r);
    float fL = f.g + .5 * (f.b + f.r);
    float hL = h.g + .5 * (h.b + h.r);
    // Noise detection.
    float nz = .25 * (bL + dL + fL + hL) - eL;
    nz=clamp(
        abs(nz)
        /(
            max(max(bL,dL),max(eL,max(fL,hL)))
            -min(min(bL,dL),min(eL,min(fL,hL)))
        ),
        0., 1.
    );
    nz=1.-.5*nz;
    // Min and max of ring.
    vec4 mn4 = min(e, min(min(b, d), min(f, h)));
    vec4 mx4 = max(e, max(max(b, d), max(f, h)));
    // Immediate constants for peak range.
    vec2 peakC = vec2(1., -4.);
    // Limiters, these need to be high precision RCPs.
    vec4 hitMin = mn4 / max(vec4(0.00001), 4. * mx4);
    vec4 hitMax = (peakC.x - mx4) / min(vec4(-0.00001), (4.* mn4 + peakC.y));
    vec4 lobeRGB = max(-hitMin, hitMax);
    float lobe = max(
        -FSR_RCAS_LIMIT,
        min(max(lobeRGB.r, max(lobeRGB.g, lobeRGB.b)), 0.)
    )*con;
    // Apply noise removal.
    #ifdef FSR_RCAS_DENOISE
    lobe *= nz;
    #endif
    // Resolve, which needs the medium precision rcp approximation to avoid visible tonality changes.
    return (lobe * (b + d + h + f) + e) / (4. * lobe + 1.);
}


vec4 FsrRcasLoadF(vec2 p) {
    return texture(iChannel0,p/iResolution.xy);
}

void main()
{
    vec4 fragCoord = gl_FragCoord;
    // Normalized pixel coordinates (from 0 to 1)
    vec2 uv = fragCoord.xy/iResolution.xy;

    // Set up constants
    float con;
    // float sharpness = 0.2;
    // float division = 0.5+.3*sin(iTime*.3);
    // if (iMouse.z > 0.) {
    //     sharpness = 2.-2.*pow( iMouse.y / iResolution.y,.25);
    //     division = iMouse.x / iResolution.x;
    // }
    FsrRcasCon(con,sharpness);

    // Perform RCAS pass
    vec4 col = FsrRcasF(fragCoord.xy, con);

    // Source image
    // vec2 uv1;

    // Bilinear interpolation
    // uv1 = fragCoord.xy/iResolution.xy;

    // Nearest pixel
    // uv1 = (floor(vec2(textureSize(iChannel1,0))*fragCoord.xy/iResolution.xy)+.5)/vec2(textureSize(iChannel1,0));

    // vec4 col_orig = texture(iChannel1,uv1).xyz;

    // Comparison tool
    // if (fragCoord.x/iResolution.x > division) col = col_orig;
    // if (abs(fragCoord.x/iResolution.x - division)<.005) col = vec4(0);

    fragColor = vec4(clamp(col.rgb, vec3(0.0), vec3(clamp(col.a, 0.0, 1.0))), clamp(col.a, 0.0, 1.0));
}
